/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */

export interface ClubDetailDto {
  id: number;
  tournamentId: number;
  name: string;
  memberCount: number;
}
