/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */
import type { DisciplineDetailDtoValue } from "./disciplineDetailDtoValue";

export interface DisciplineDetailDto {
  id: number;
  tournamentId: number;
  name: string;
  amountOfBestRoundsToShow: number;
  areGendersSeparated: boolean;
  showInResults: boolean;
  values: DisciplineDetailDtoValue[];
}
