/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */
import type { DisciplineEditDtoValue } from "./disciplineEditDtoValue";

export interface DisciplineEditDto {
  name: string;
  amountOfBestRoundsToShow: number;
  areGendersSeparated: boolean;
  values: DisciplineEditDtoValue[];
}
