/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from "./gender";
import type { ParticipantDetailDtoDiscipline } from "./participantDetailDtoDiscipline";

export interface ParticipantDetailDto {
  id: number;
  name: string;
  startNumber: number;
  gender: Gender;
  clubId: number;
  clubName: string;
  disciplines: ParticipantDetailDtoDiscipline[];
}
