/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from "./gender";

export interface ParticipantEditDto {
  name: string;
  startNumber: number;
  gender: Gender;
  clubId: number;
}
