/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */

export interface ParticipantResultDetailDtoDisciplineValue {
  name: string;
  isAdded: boolean;
}
