/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */

export type ScoreboardDataTableColumnIWidthFixedType =
  (typeof ScoreboardDataTableColumnIWidthFixedType)[keyof typeof ScoreboardDataTableColumnIWidthFixedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScoreboardDataTableColumnIWidthFixedType = {
  fixed: "fixed",
} as const;
