/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */
import type { ScoreboardDataTableColumn } from "./scoreboardDataTableColumn";
import type { ScoreboardDataTableRow } from "./scoreboardDataTableRow";

export interface ScoreboardDataTable {
  id: string;
  name: string;
  columns: ScoreboardDataTableColumn[];
  rows: ScoreboardDataTableRow[];
}
