/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */
import type { ScoreboardDataTable } from "./scoreboardDataTable";

export interface ScoreboardData {
  tournamentName: string;
  tables: ScoreboardDataTable[];
}
