/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */
import type { ScoreboardDataTableColumnIWidthFixedType } from "./scoreboardDataTableColumnIWidthFixedType";

export interface ScoreboardDataTableColumnIWidthFixed {
  type: ScoreboardDataTableColumnIWidthFixedType;
  width: number;
}
