/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */

export type ScoreboardDataTableColumnIWidthVariableType =
  (typeof ScoreboardDataTableColumnIWidthVariableType)[keyof typeof ScoreboardDataTableColumnIWidthVariableType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScoreboardDataTableColumnIWidthVariableType = {
  variable: "variable",
} as const;
