/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */
import type { ScoreboardDataTableColumnIWidthVariableType } from "./scoreboardDataTableColumnIWidthVariableType";

export interface ScoreboardDataTableColumnIWidthVariable {
  type: ScoreboardDataTableColumnIWidthVariableType;
  weight: number;
}
