/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung.Server
 * OpenAPI spec version: 1.0.0
 */
import type { TeamScoreDisplayType } from "./teamScoreDisplayType";

export interface TeamDisciplineEditDto {
  name: string;
  displayType: TeamScoreDisplayType;
  basedOn: number[];
}
