/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */

export type TeamScoreDisplayType =
  (typeof TeamScoreDisplayType)[keyof typeof TeamScoreDisplayType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamScoreDisplayType = {
  Normal: "Normal",
  Nationcup: "Nationcup",
} as const;
