/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */
import type { TeamDisciplineDetailDtoDiscipline } from "./teamDisciplineDetailDtoDiscipline";
import type { TeamScoreDisplayType } from "./teamScoreDisplayType";

export interface TeamDisciplineDetailDto {
  name: string;
  displayType: TeamScoreDisplayType;
  basedOn: TeamDisciplineDetailDtoDiscipline[];
}
