/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Turnierverwaltung
 * OpenAPI spec version: 1.0.0
 */

export interface TournamentDetailDto {
  id: number;
  name: string;
  date: number;
  teamSize: number;
  isTeamSizeFixed: boolean;
  clubCount: number;
  disciplineCount: number;
  participantCount: number;
  teamCount: number;
}
