export const tournamentsQueryKey = () => ["tournaments"];
export const tournamentQueryKey = (tournamentId: number) => ["tournament", tournamentId];
export const clubsQueryKey = (tournamentId: number) => ["clubs", tournamentId];
export const clubQueryKey = (clubId: number) => ["club", clubId];
export const disciplinesQueryKey = (tournamentId: number) => ["disciplines", tournamentId];
export const disciplineQueryKey = (disciplineId: number) => ["discipline", disciplineId];
export const participantsQueryKey = (tournamentId: number) => ["participants", tournamentId];
export const participantQueryKey = (participantId: number) => ["participant", participantId];
export const participantResultsQueryKey = (participantId: number, disciplineId: number) => ["participantResults", participantId, disciplineId];
export const teamDisciplinesQueryKey = (tournamentId: number) => ["team_disciplines", tournamentId];
export const teamDisciplineQueryKey = (teamDisciplineId: number) => ["team_discipline", teamDisciplineId];