POST http://localhost:5097/api/tournaments/1/overview/download
Content-Type: application/json

{
  "tablesToExport": [
    "Test Disziplin 0",
    "Test Disziplin 1",
    "Test Disziplin 2",
    "Test Disziplin 3",
    "Test Disziplin 4"
  ],
  "separateDocuments": false
}