name: Build Backend

on:
  push:
    paths:
      - "backend/**"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
        