name: Build

on:
  push:

jobs:
  build_fronted:
    name: Build Frontend
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build

  build_backend:
    name: Build Backend
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
  
  build_docker:
    name: Build Docker
    runs-on: "ubuntu-latest"
    needs: 
      - build_fronted
      - build_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Build images
        uses: docker/bake-action@v4.1.0
        
        