name: Build

on:
  push:

jobs:
  build_fronted:
    name: Build Frontend
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: backend/pnpm-lock.yaml
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Build
        run: pnpm run build

  build_backend:
    name: Build Backend
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: backend/pnpm-lock.yaml
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Build
        run: pnpm run build
      - name: Run Tests
        run: pnpm run test
  
  build_docker:
    name: Build Docker
    runs-on: "ubuntu-latest"
    needs: 
      - build_fronted
      - build_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Build images
        uses: docker/bake-action@v4.3.0
        
        