name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "Client/package.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "Client/package.json"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: "Client/pnpm-lock.yaml"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: |
            Server/packages.lock.json
            Server.Tests/packages.lock.json

      - name: Install Node.js Dependencies
        working-directory: ./Client
        run: pnpm install --frozen-lockfile
      
      - name: Restore .NET Packages
        run: dotnet restore --locked-mode
      
      - name: Build Server
        working-directory: ./Server
        run: dotnet publish --no-restore /p:PublishProfile=Properties/PublishProfiles/Win_x64.xml
      
      - name: Upload Server
        uses: actions/upload-artifact@v4
        with:
          name: Server
          path: ./Server/bin/Release/net9.0/win-x64/publish/