name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-scoreboard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "scoreboard/package.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "scoreboard/package.json"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: "scoreboard/pnpm-lock.yaml"
      
      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: scoreboard/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('scoreboard/pnpm-lock.yaml') }}-${{ hashFiles('scoreboard/**/*.js', 'scoreboard/**/*.jsx', 'scoreboard/**/*.ts', 'scoreboard/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('scoreboard/pnpm-lock.yaml') }}-
      
      - name: Install dependencies
        working-directory: scoreboard
        run: pnpm install
      
      - name: Build scoreboard
        working-directory: scoreboard
        run: pnpm run build
      
      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: Scoreboard
          path: scoreboard/dist/
          retention-days: 1
  
  build-program:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    needs: build-scoreboard
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: Scoreboard
          path: scoreboard/dist/
      
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: app
        run: chmod +x gradlew

      - name: Build program
        working-directory: app
        run: ./gradlew createDistributable
      
      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: Program-${{ matrix.os }}
          path: app/build/compose/binaries/main/app